steps:
# Uses the ubuntu build step:
# to run a shell script; and
# set env variables for its execution
- name: 'ubuntu'
  id: set_up_env_variables
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT_ID=$PROJECT_ID'
# step2
# To Clone the repository 
- name: 'gcr.io/cloud-builders/git'
  waitFor: ['set_up_env_variables']
  args: ['clone', '--single-branch', '--branch',
         'master', 'https://source.developers.google.com/p/mlops-pipeline/r/sg-mlops']
  id: 'Clone Repository'  
# step3
# use python build step , use pip3 entry point to install required libraries from requirements.txt file
- name: python
  waitFor: ['Clone Repository']
  id: installation_pip
  entrypoint: pip3
  args: ["install", "-r", "requirements.txt","--user"]
# step4
#use python build to run the python compiler file fom src directory to generate pipeline json 
- name: python
  waitFor: ['installation_pip']
  id: pipeline_compiler
  entrypoint: python3
  args: ["src/python_test.py"]
